name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy-documentation:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build docker image
        run: docker build . -t homepage
      - name: Build documentation
        run: docker run --rm -v .:/docs homepage
      - name: Sync files with production server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_host: sdelquin.matraka.es
          remote_path: ${{ secrets.REMOTE_BUILD_PATH }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
